name: request_queue_and_completer
description: Request queue and completer example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  elementary: ^1.5.0
  flutter:
    sdk: flutter
  surf_lint_rules: ^1.5.0
  synchronized: ^3.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4

flutter:
  uses-material-design: true